### ISSUE TITLE
how to set header and footer.??

### ISSUE THREAD

**Issue by BeanMc** [rknell/url2pdf#3]

**Comment by rknell** [comment]
Hi Sorry, not sure you can. If you want to look into and create a pull
request if its possible that would be great.

Alternatively you could create a header and footer into html. This very old
stackoverflow article says that you can put a position fixed in your html
and it will repeat on every page

http://stackoverflow.com/questions/1360869/how-to-use-html-to-print-header-and-footer-on-every-printed-page-of-a-document


<http://www.snappy-apps.com.au>
